name: Build packages and check API changes

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build packages
        id: build
        run: yarn build-packages:ci
