name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

# id-token is required for OIDC
# See https://docs.npmjs.com/trusted-publishers
permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # OIDC requires npm 11.5.1 or later
      # Changesets calls npm to publish packages
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Update Release PR or Release to NPM
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Workaround for changesets setting NPM_TOKEN in the registry URL
          # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
          NPM_TOKEN: ''
